### PR TITLE
Fix flags and add directors names

### LINKED ISSUE #65: UI: show country flags

### PR DESCRIPTION
**Pull request by nia-ja**
Closes #65 
- add flag icons for countries
- add tooltip with country name to the flags
- add directors names to the movie card
- fix mapping of Czechoslovakia to CZ

### CODE REVIEW

File: ui/scripts/movie.js [hunk 1]
```diff
@@ -109,6 +123,31 @@ export default class Movie {
         return conteiner;
     }
 
+    // expects countries object that has name and flag fields, class  
+    getFlags(counries, name) {
```
Comment (booxter) [inline ui/scripts/movie.js:127]: `countries`

File: ui/scripts/movie.js [hunk 2]
```diff
@@ -109,6 +123,31 @@ export default class Movie {
...
+        let flags = "";
+
+        if (counries.length !== 0) {
```
Comment (booxter) [inline ui/scripts/movie.js:130]: it's usually better to avoid indentation levels by returning earlier. E.g. here you could:

```
if (countries.length == 0) {
  return "";
}
<proceed handling the list>
```

File: ui/scripts/movie.js [hunk 3]
```diff
@@ -109,6 +123,31 @@ export default class Movie {
...
+            const list = document.createElement("ul");
+            list.classList.add(name);
+
+            counries.map(country => {
+                if (country.flag) {
```
Comment (booxter) [inline ui/scripts/movie.js:135]: nit: you access `country.flag` twice: here and in the next line. It's usually better to avoid repeating the work by extracting a value once. E.g.:

```
flag = country.flag;
if (flag) {
  flags += `...{flag}...`
}
```

(but see the other suggestion below that makes this comment not needed)

File: ui/scripts/movie.js [hunk 4]
```diff
@@ -109,6 +123,31 @@ export default class Movie {
...
+                    flags += `<li class="country-flag">${country.flag}<span class="country-name-tooltip">${country.name}</span></li>`;
+                } else {
+                    // handle null flag
+                    // &#127987; adds white flag symbol
+                    flags += `<li class="country-flag">&#127987;<span class="country-name-tooltip">${country.name}</span></li>`;
```
Comment (booxter) [inline ui/scripts/movie.js:140]: in general, you should not repeat yourself, so instead of maintaining the format string for the list element here and above, you could:

```
flag = country.flag || defaultFlag;
flags += `<li class="country-flag">{flag}<span class="country-name-tooltip">${country.name}</span></li>`;
```

Comment (booxter) [inline ui/scripts/movie.js:140]: These html character codes embedded in code are a bit concerning. Can we start defining them somewhere in a common module as variables with meaningful names, then refer here? (Same for right arrow merged in another PR.)

File: ui/scripts/movie.js [hunk 5]
```diff
@@ -94,6 +95,19 @@ export default class Movie {
...
     }
 
+    createDirectorsList(names) {
+        const conteiner = document.createElement('h2');
+        conteiner.classList.add("movie-directors");
+
+        if(names !== "") {
+            let dirNamesStr = names.map(String).join(', ');
+            let result = `Directed by <span class="directors-names">${dirNamesStr}</span>`;
+            conteiner.innerHTML = result;
```
Comment (booxter) [inline ui/scripts/movie.js:105]: `container`

File: ui/scripts/movie.js [hunk 6]
```diff
@@ -94,6 +95,19 @@ export default class Movie {
         return movieInfoConteiner;
     }
 
+    createDirectorsList(names) {
+        const conteiner = document.createElement('h2');
+        conteiner.classList.add("movie-directors");
+
+        if(names !== "") {
```
Comment (booxter) [inline ui/scripts/movie.js:102]: isn't `names` here an iterable? why do we compare it with a string?

**Review by booxter — CHANGES_REQUESTED** [review]

File: ui/scripts/movie.js (hunk 4 above)
Comment (nia-ja) [reply ui/scripts/movie.js:140]: We can do it as a separate PR. I'll add an issue for that and will work on it

File: ui/scripts/movie.js (hunk 6 above)
Comment (nia-ja) [reply ui/scripts/movie.js:102]: good point, fixed

File: ui/scripts/movie.js [hunk 7]
```diff
@@ -127,25 +127,21 @@ export default class Movie {
...
-                    // handle null flag
-                    // &#127987; adds white flag symbol
-                    flags += `<li class="country-flag">&#127987;<span class="country-name-tooltip">${country.name}</span></li>`;
-                }
-            })
-            list.innerHTML = flags;
-            return list;
-        } else {
+        if (countries.length == 0) {
             return flags;
```
Comment (booxter) [inline ui/scripts/movie.js:131]: nit: it's usually better to initialize variables as late as possible. For example, you don't need `flags` here, you could just return "". And then initialize `flags` later, below the `if` block.

File: ui/scripts/movie.js [hunk 8]
```diff
@@ -127,25 +127,21 @@ export default class Movie {
...
         }
 
+        const list = document.createElement("ul");
+        list.classList.add(name);
+
+        countries.map(({flag, name} = country) => {
+            // let {flag, name} = country;
```
Comment (booxter) [inline ui/scripts/movie.js]: ?

File: ui/scripts/movie.js [hunk 9]
```diff
@@ -127,25 +127,21 @@ export default class Movie {
...
+            // &#127987; adds white flag symbol
+            flag = flag || "&#127987;";
```
Comment (booxter) [inline ui/scripts/movie.js:139]: please move it to a variable with a name like `whiteFlag`.

File: ui/scripts/movie.js [hunk 10]
```diff
@@ -99,7 +99,7 @@ export default class Movie {
         const container = document.createElement('h2');
         container.classList.add("movie-directors");
 
-        if(names !== "") {
+        if(names) {
```
Comment (booxter) [inline ui/scripts/movie.js:102]: don't you add spaces after `if`s in js?
